Issues 103 bondar
SergeyKutsko/universal_auto pull request #142
Opened 2023-03-09 12:48 UTC by OlegBondarUA

fix bug

2023-03-09 12:49 UTC, OlegBondarUA commented
@SergeyKutsko

2023-03-09 13:05 UTC, SergeyKutsko requested changes
@OlegBondarUA it will not work. You even not setup Telegram webhook URL.

2023-03-09 13:22 UTC, OlegBondarUA commented
i setup webhook via https://api.telegram.org/bot{TOKEN}/setWebhook?url={DOMEN}/webhook/

so the bot worked or you want settings through
updater.startwebhook()?

@SergeyKutsko

2023-03-09 16:13 UTC, OlegBondarUA commented
додав настройку веб хука через команду start_webhook
@SergeyKutsko

2023-03-13 11:22 UTC, OlegBondarUA commented
я виправив та добавив метод start_webhook 
налаштував так для тесту на локальній машині
використав ngrok який слухає 8000 порт на якому було запущено проект в докері 
далі url який дає ngrok я використав у файді .env добавив WEBHOOK_URL = "https://a1e5-5-1-12-217.eu.ngrok.io" 
та ще добавив ALLOWED_HOSTS = "a1e5-5-1-12-217.eu.ngrok.io"
таким чином при запуску в мене вебхук налаштовувався на "https://a1e5-5-1-12-217.eu.ngrok.io/webhook"
у методі start_webhook. 
для вебхука використовується функція webhook я приймає та обробляє і виконує команди бота

@WARGDOOM

2023-03-14 07:55 UTC, OlegBondarUA commented
@SergeyKutsko

2023-03-14 19:34 UTC, merged