Managet dashboard
SergeyKutsko/universal_auto pull request #390
Opened 2023-09-06 08:08 UTC by OlegBondarUA

Оновив отримання данних та додав інфоормацію про водіїв

@WARGDOOM

2023-09-06 13:55 UTC, KurochkaR requested changes

2023-09-06 14:25 UTC, OlegBondarUA commented on taxi_service/views.py
>          elif action == 'get_role':
done

2023-09-07 07:07 UTC, SpaceIgor approved these changes

2023-09-07 07:17 UTC, KurochkaR approved these changes

2023-09-07 09:30 UTC, merged